apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongo-dev

spec:
  #type: LoadBalancer
  selector:
    pp: mongo-express
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    #nodePort: 30000
