apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo-dev
spec:
  capacity:
    storage: 10Gi
  accessMode:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/mongo