---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-prod

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-configmap
  namespace: nodejs-prod
data:
  DB_NAME: "recon"
  DB_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata: 
  name: nodejs-secret
type: Opaque
data:
  DB_USERNAME: "root"
  DB_PASSWORD: "eW91cl9wYXNzd29yZA=="  