---
kind: Namespace
apiVersion: v1
metadata:
  name: nodejs-dev

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nodejs-config-map
  namespace: nodejs-dev
data:
  DB_NAME: "recon"
  DB_PORT: "3306"

---
kind: Secret
apiVersion: v1
metadata: 
  name: nodejs-secret
  namespace: nodejs-dev
type: Opaque
data:
  DB_USERNAME: "app_user"
  DB_PASSWORD: "cGFzc3dvcmQ="

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-deployment
  namespace: nodejs-dev
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-app
        image: node:22
        ports:
        - cointainerPort: 8888
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nodejs-config-map
              value: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejs-config-map
              value: DB_PORT
              
    
        



