apiVersion: v1
kind: Namespace
metadata:
  name: python-prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-prod
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
          app: python
    spec:
      containers:
      - name: python
        image: python3:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: db-url

---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: python-prod
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 3000

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: python-prod
type: Opaque
data:
  mysql_user: ####
  mysql_password: ####

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: python-prod
data:
  db-url: ######

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: python-prod
  labels:
    app: mysql-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql-8
        ports:
        - containerPort: 3306 

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: python-prod
data:
  selector:
    app: mysql-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  


      

      
