apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: python
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres_password
        - name: POSTGRES_URL
          valueFrom:
            name: postgres-configmap
            value: 

---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    matchLabels:
      app: python-app
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db 
  labels:
    app: postgres-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    containers:
    - name: postgres-db
      image: postgres
      ports:
      - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  app: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
    ports:
    - protocol: TCP
      port: 9090
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-configmap
data:
  database_url: postgres-service

---
apiVersion: v1
kind: Secret
metadata:
  name: python-Secret
data:
  postgres_user: #######
  postgres_password: ######
