apiVersion: app/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    containers:
    - name: python
      image: python
      ports:
      - containerPort: 8080
      env:
      - name: POSTGRES_USER
        value:
      - name: POSTGRES_PASSWORD
        value:
      - name: POSTGRES_URL
        value:

---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    matchLabels:
      app: python-app
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: postgres-db 
  labels:
    app: postgres-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    containers:
    - name: postgres-db
      image: postgres
      ports:
      - containerPort: 5432
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-configmap
data:
  database_url: postgres-service



