apiVersion: v1
kind: Namespace
metadata:
  name: python-prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-prod
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
    template:
      metadata:
        labels:
          app: python
    spec:
      containers:
      - name: python
        image: python3:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: db-url

---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: python-prod
spec:
  type: LoadBalance
  selector:
    matchLabels:
      app: python
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: configmap
metadata:
  name: mysql-configmap
  namespace: python-prod
data:
  db-url: ######

      

      
