apiVersion: v1
kind: Namespace
metadata:
  name: java-app

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: java-app
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: java-app
data:
  mysql-db: backend

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: java-app
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-StatefulSet
  namespace: java-app
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-db 
      volumeClaimTemplates:
      - metadata:
          name: mysql-storage
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: manual
          resources:
            requests:
              storage: 10Gi
---            
apiVersion:
name: Service
metadata:
  name: mysql-svc
  namespace: java-app
spec:
  selectors:
    app: mysql-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: java-app
  labels:
    app: java
spec:
  replicas: 2
  selectors:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: java:latest
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-db

---
apiVersion: v1
kind: Service
metadata:
  name: java-svc
  namespace: java-app
spec:
  type: LoadBalancer
  selector:
    app: java
  ports:
  - protocol: TCP
    port: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: "dashboard.com"
    http:
      paths:
      - pathType: Prefix
        path: "/app"
        backend:
          service:
            name: java-svc
            port:
              number: 3000

