apiVersion: v1
kind: Namespace
metadata:
  name: java-app

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: java-app
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-StatefulSet
  namespace: java-app
spec:
  replicas: 2
  selectors:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      cointainers:
      - name: mysql-db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          secretKeyRef:
            name: mysql-secret
            key: mysql-root-password
      
apiVersion:
name: Service
metadata:
  name: mysql-svc
  namespace: java-app
spec:
  selectors:
    app: mysql-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306