apiVersion: v1
kind: service
metadata:
  name: mysql-service
  namespace: nodejs-prod
spec:
  selector:
    matchLabels:
      app: mysql-db
    ports:
    - protocol: TCP
      targetPort: 3306
      port: 3306
  