apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: nodejs-prod
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeClaimPolicy: Retain
  storageClass: manual
  hostPath:
    path: /var/lib/mysql
