apiVersion: v1
kind: Service
metadata:
  name: nodejs-service

spec:
#  type: Loadbalancer
  selector:
    matchLabels:
      app: nodejs
    ports:
    - protocol: TCP
      targetPort: 8888
      port: 80 