---
kind: Namespace
apiVersion: v1
metadata:
  name: nodejs-dev

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nodejs-config-map
  namespace: nodejs-dev
data:
  DB_PORT: "53306"
  DB_NAME: "recon"

---
kind: Secret
apiVersion: v1
metadata: 
  name: nodejs-secret
  namespace: nodejs-dev
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: FNWIEB32844B=

---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: nodejs-backend-deployment
  namespace: nodejs-dev
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nodejs-app
        image: node:alphine
        ports:
        - containerPort: 8888
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nodejs-config-map
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejs-config-map
              key: DB_PORT  
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nodejs-secret
              key: DB_USER           
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodejs-secret
              key: DB_PASSWORD

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-api-deployment
  namespace: nodejs-dev
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: node:alphine
        ports:
        - containerPort: 8090

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: frontend-deployment-hpa
  namespace: nodejs-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextjs-frontent-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextjs-frontent-deployment
  namespace: nodejs-dev
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nextjs-app
        image: vulhub/nextjs:15.5.6
        ports: 
        - containerPort: 8888
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nodejs-config-map
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejs-config-map
              key: DB_PORT  
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nodejs-secret
              key: DB_USER           
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodejs-secret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-service
  namespace: nodejs-dev
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-api-service
  namespace: nodejs-dev
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: nextjs-service
  namespace: nodejs-dev
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8888
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nodejs-ingress
  namespace: nodejs-dev
spec:
  rules:
  - host: abc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service
            port:
              number: 3000
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: nodejs-service
            port: 
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: nodejs-api-service
            port:
              number: 8090
    



